In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [3]:
n1=np.arange(2,20,2)

In [4]:
n1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
n1=np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#np.full is use to print a specific num for given row and coloumn

In [7]:
n2=np.full((3,4),3)

In [8]:
n2

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [9]:
#np.arange will create a array of given range with given step size

In [10]:
n3=np.arange(0,11,2)
n3

array([ 0,  2,  4,  6,  8, 10])

In [11]:
#for array of specific range for given no of elements we can use randomint 

In [12]:
from random import  randint
n4=np.random.randint(1,100,13)#1 to 100 is range and any random no of elements we want is 13 
n4

array([77, 61, 30, 26, 69,  6, 31, 96, 32, 16, 23, 11,  9])

In [13]:
n5=np.array([[4,5,6],[2,3,6]])

In [14]:
n5

array([[4, 5, 6],
       [2, 3, 6]])

In [15]:
n5.shape#we can the shape also

(2, 3)

In [16]:
n5.shape=(3,2)

In [17]:
n5

array([[4, 5],
       [6, 2],
       [3, 6]])

In [18]:
n6=np.array([1,2,3,4,5])
n7=np.array([6,7,8,9,10])

In [19]:
np.vstack((n6,n7))#for vertically 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
np.hstack((n6,n7))#for horizontly add two array's

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.column_stack((n6,n7))#for column stack

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [22]:
#intersection
n8=np.array([10,20,30,50,40,60])
n9=np.array([50,60,70,80,90,30])
np.intersect1d(n8,n9)#1d for one dimentional

array([30, 50, 60])

In [23]:
#difference
np.setdiff1d(n8,n9)#diff element in n8 than n9

array([10, 20, 40])

In [24]:
np.setdiff1d(n9,n8)#diff element in n9 than n8

array([70, 80, 90])

In [25]:
#lets do some math with array
import numpy as np
n1=np.array([1,2,3])
n2=np.array([4,5,6])

In [26]:
np.sum(n1,n2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [27]:
np.sum((n1,n2),axis=0)#for column

array([5, 7, 9])

In [28]:
np.sum((n1,n2),axis=1)#for row addition

array([ 6, 15])

In [29]:
n1

array([1, 2, 3])

In [30]:
n1=n1+5

In [31]:
n1

array([6, 7, 8])

In [32]:
n1=n1*5
n1

array([30, 35, 40])

In [33]:
n1=n1/2
n1

array([15. , 17.5, 20. ])

In [34]:
n1=n1-5

In [35]:
n1

array([10. , 12.5, 15. ])

In [36]:
#lets perform some mathematical functions

In [37]:
n1=np.array([1,2,3,4,5,6,7,8,9])
n1=n1*3

In [38]:
np.mean(n1)

15.0

In [39]:
np.median(n1)

15.0

In [40]:
np.std(n1)

7.745966692414834

In [41]:
n1=np.array([1,3,34,6,54,87,98])
n1

array([ 1,  3, 34,  6, 54, 87, 98])

In [42]:
np.save('my_array',n1)

In [43]:
n2=np.load('my_array.npy')

In [44]:
n2

array([ 1,  3, 34,  6, 54, 87, 98])

In [45]:
n3=np.array([[1,2,3,4],[1,2,3,4],[8,9,6,5]])
n3

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [8, 9, 6, 5]])

In [46]:
np.transpose(n3)

array([[1, 1, 8],
       [2, 2, 9],
       [3, 3, 6],
       [4, 4, 5]])

In [47]:
n3

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [8, 9, 6, 5]])

In [48]:
n3[0]

array([1, 2, 3, 4])

In [49]:
n3[:,1][2]

9

In [50]:
n4=np.array([[1,2,3],[1,2,3],[8,9,6],[1,2,3]])
n4

array([[1, 2, 3],
       [1, 2, 3],
       [8, 9, 6],
       [1, 2, 3]])

In [51]:
n4.dot(n3)

array([[27, 33, 27, 27],
       [27, 33, 27, 27],
       [65, 88, 87, 98],
       [27, 33, 27, 27]])

In [52]:
n3.dot(n4)

array([[ 31,  41,  39],
       [ 31,  41,  39],
       [ 70,  98, 102]])

THANKS FOR GOING THROUGH THIS ......sairaj naikwadi